package com.jiangfengliu.model;

import java.time.LocalDateTime;

public class Channel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haoke..channel.id
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haoke..channel.is_del
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haoke..channel.create_time
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haoke..channel.update_time
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haoke..channel.display_name
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haoke..channel.note_name
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    private String noteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column haoke..channel.is_handpick
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    private Integer isHandpick;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haoke..channel.id
     *
     * @return the value of haoke..channel.id
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haoke..channel.id
     *
     * @param id the value for haoke..channel.id
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haoke..channel.is_del
     *
     * @return the value of haoke..channel.is_del
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haoke..channel.is_del
     *
     * @param isDel the value for haoke..channel.is_del
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haoke..channel.create_time
     *
     * @return the value of haoke..channel.create_time
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haoke..channel.create_time
     *
     * @param createTime the value for haoke..channel.create_time
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haoke..channel.update_time
     *
     * @return the value of haoke..channel.update_time
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haoke..channel.update_time
     *
     * @param updateTime the value for haoke..channel.update_time
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haoke..channel.display_name
     *
     * @return the value of haoke..channel.display_name
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haoke..channel.display_name
     *
     * @param displayName the value for haoke..channel.display_name
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haoke..channel.note_name
     *
     * @return the value of haoke..channel.note_name
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public String getNoteName() {
        return noteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haoke..channel.note_name
     *
     * @param noteName the value for haoke..channel.note_name
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public void setNoteName(String noteName) {
        this.noteName = noteName == null ? null : noteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column haoke..channel.is_handpick
     *
     * @return the value of haoke..channel.is_handpick
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public Integer getIsHandpick() {
        return isHandpick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column haoke..channel.is_handpick
     *
     * @param isHandpick the value for haoke..channel.is_handpick
     *
     * @mbg.generated Thu Apr 18 14:44:37 CST 2019
     */
    public void setIsHandpick(Integer isHandpick) {
        this.isHandpick = isHandpick;
    }
}